# Languages

## Binary

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = ['Vinarise']

## Ruby
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'
hook_source = '''
  let g:neomake_ruby_enabled_makers = ['rubocop']
  let g:ref_refe_cmd = substitute(system('(cd ' . expand("%:h") . '; rbenv which refe)'), '\n\+$', '', '')
'''

[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

## HTML
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = 'html'

## CSS
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

## JavaScript
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'
hook_source = '''
  let g:neomake_javascript_eslint_maker = {
  \     'exe': 'eslint',
  \     'args': ['-f', 'compact'],
  \     'errorformat': '%E%f: line %l\, col %c\, Error - %m,' .
  \                    '%W%f: line %l\, col %c\, Warning - %m'
  \     }
  let g:neomake_javascript_enabled_makers = ['eslint']
'''

## Rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

## Haskell
[[plugins]]
repo = 'dag/vim2hs'
on_ft = 'haskell'

## TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

## TeX
[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'

[[plugins]]
repo = 'matze/vim-tex-fold'
on_ft = 'tex'
