[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  au AutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#on_i = 1
#hook_source = '''
#  let g:deoplete#omni_patterns = {}
#  let g:deoplete#enable_at_startup = 1
#'''

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  let g:EasyMotion_do_mapping = 0
  let g:EasyMotion_smartcase = 1
  nmap f <plug>(easymotion-overwin-f2)
'''

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
  autocmd! BufWritePost * Neomake
  let g:neomake_markdown_textlint_maker = {
  \     'exe': 'textlint',
  \     'args': ['--format', 'compact',
  \              '--rule', 'no-mix-dearu-desumasu',
  \              '--rule', 'max-ten',
  \              '--rule', 'spellcheck-tech-word',
  \             ],
  \     'errorformat': '%f: line %l\, col %c\, %m',
  \   }
  let g:neomake_markdown_enabled_makers = ['textlint']
'''

#[[plugins]]
#repo = 'thinca/vim-ref'
#hook_add = "let g:ref_refe_cmd = system('which refe')"

[[plugins]]
repo = 'Shougo/vinarise.vim'


[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'
hook_source = '''
  let g:neomake_ruby_enabled_makers = ['rubocop']
'''

#[[plugins]]
#repo = 'yuku-t/vim-ref-ri'
#on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'dag/vim2hs'
on_ft = 'haskell'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'
hook_source = '''
  let g:neomake_javascript_eslint_maker = {
  \     'exe': 'eslint',
  \     'args': ['-f', 'compact'],
  \     'errorformat': '%E%f: line %l\, col %c\, Error - %m,' .
  \                    '%W%f: line %l\, col %c\, Warning - %m'
  \     }
  let g:neomake_javascript_enabled_makers = ['eslint']
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
