[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'neomake/neomake'
hook_add = "autocmd! BufWritePost * Neomake"

[[plugins]]
repo = 'thinca/vim-ref'
hook_add = "let g:ref_refe_cmd = system('which refe')"

[[plugins]]
repo = 'Shougo/vinarise.vim'
