[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'benekastah/neomake'
hock_add = '''
  autocmd! BufWritePost * Neomake
'''

[[plugins]]
repo = 'thinca/vim-ref'
