[[plugins]]
repo = 'Shougo/dein.vim'

# Appearance

[[plugins]]
repo = 'yantene/molokai'
hook_add = 'au cs_hook VimEnter * nested colorscheme molokai'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = { 'colorscheme': 'wombat' }
'''

# Controll

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  let g:EasyMotion_do_mapping = 0
  let g:EasyMotion_smartcase = 1
  nmap f <plug>(easymotion-overwin-f2)
'''

[[plugins]]
repo = 'tmhedberg/matchit'

# Completion

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  inoremap <expr><tab> pumvisible() ? "\<C-n>" : "\<tab>"
'''
on_i = 1
# Note: Execute the :UpdateRemotePlugins and restart Neovim.

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev  = 'next'
build = 'bash install.sh'
hook_add = '''
  set hidden
  let g:LanguageClient_serverCommands = {
  \ 'rust': ['rustup', 'run', 'stable', 'rls'],
  \ 'ruby': ['solargraph', 'stdio'],
  \ 'vue': ['vls'],
  \ 'javascript': ['javascript-typescript-stdio'],
  \}
  let g:LanguageClient_autoStart = 1
  nnoremap <F5>          :call LanguageClient_contextMenu()<CR>
  nnoremap <silent> K    :call LanguageClient#textDocument_hover()<CR>
  nnoremap <silent> gd   :call LanguageClient#textDocument_definition()<CR>
  nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
'''

# Lint

[[plugins]]
repo = 'w0rp/ale'

# Ref

[[plugins]]
repo = 'thinca/vim-ref'

# Tools

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

# Languages

## Binary

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = ['Vinarise']

## Ruby

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'
hook_source = '''
  let g:ref_refe_cmd = substitute(system('(cd ' . expand("%:h") . '; rbenv which refe)'), '\n\+$', '', '')
'''

[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'vim-utils/vim-ruby-fold'
on_ft = 'ruby'

## Web

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = 'html'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

## JSON

repo = 'elzr/vim-json'
on_ft = 'json'
hook_source = '''
  let g:vim_json_syntax_conceal = 0
'''

## Elixir

[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = 'elixir'

## Rust

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

## Haskell

[[plugins]]
repo = 'dag/vim2hs'
on_ft = 'haskell'

[[plugins]]
repo = 'ujihisa/neco-ghc'
on_ft = 'haskell'

## CSV

[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = 'csv'

## TOML

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

## TeX

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'

[[plugins]]
repo = 'matze/vim-tex-fold'
on_ft = 'tex'
